import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Download, Eye, LayoutDashboard } from "lucide-react";
import ProfileSummary from "./ProfileSummary";
import InsightsPanel from "./InsightsPanel";
import SuggestionsPanel from "./SuggestionsPanel";
import type { AnalysisResult } from "@/types/analysis";

interface DashboardProps {
  result: AnalysisResult;
  onReset: () => void;
}

type Tab = "insights" | "suggestions" | "recruiter";

const Dashboard = ({ result, onReset }: DashboardProps) => {
  const [tab, setTab] = useState<Tab>("insights");
  const { githubData, analysis } = result;

  const handleExportPDF = () => {
    // Build a printable page
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>LexonPro Report - ${githubData.profile.login}</title>
    <style>
      body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #222; }
      h1 { color: #16a34a; } h2 { margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
      .score { font-size: 48px; font-weight: bold; color: ${analysis.portfolioScore >= 70 ? '#16a34a' : analysis.portfolioScore >= 40 ? '#ca8a04' : '#dc2626'}; }
      ul { padding-left: 20px; } li { margin: 6px 0; }
      .tag { display: inline-block; background: #f0f0f0; padding: 2px 8px; border-radius: 4px; margin: 2px; font-size: 12px; }
    </style></head><body>
    <h1>LexonPro — GitHub Analysis Report</h1>
    <p><strong>${githubData.profile.name}</strong> (@${githubData.profile.login})</p>
    <p>Portfolio Score: <span class="score">${analysis.portfolioScore}/100</span></p>
    <p>${githubData.profile.bio || ''}</p>
    <p>Repos: ${githubData.stats.totalRepos} | Stars: ${githubData.stats.totalStars} | Followers: ${githubData.profile.followers}</p>
    <h2>Skill Summary</h2><p>${analysis.skillSummary}</p>
    <h2>Strengths</h2><ul>${analysis.strengths.map(s => `<li>${s}</li>`).join('')}</ul>
    <h2>Areas to Improve</h2><ul>${analysis.weaknesses.map(w => `<li>${w}</li>`).join('')}</ul>
    <h2>Missing Skills</h2><p>${analysis.missingSkills.map(s => `<span class="tag">${s}</span>`).join(' ')}</p>
    <h2>Project Ideas</h2><ul>${analysis.projectIdeas.map(p => `<li><strong>${p.title}</strong>: ${p.description}</li>`).join('')}</ul>
    <h2>Repo Improvements</h2><ul>${analysis.repoImprovements.map(r => `<li><code>${r.repo}</code>: ${r.suggestion}</li>`).join('')}</ul>
    <h2>ATS Resume Bullets</h2><ul>${analysis.resumeBullets.map(b => `<li>${b}</li>`).join('')}</ul>
    <h2>Recruiter Perspective</h2><p><em>${analysis.recruiterInsights}</em></p>
    <h2>Career Advice</h2><p>${analysis.overallAdvice}</p>
    <hr><p style="font-size:12px;color:#999;">Generated by LexonPro — AI-Powered GitHub Analyzer</p>
    </body></html>`);
    w.document.close();
    w.print();
  };

  const tabs: { id: Tab; label: string; icon: any }[] = [
    { id: "insights", label: "AI Insights", icon: LayoutDashboard },
    { id: "suggestions", label: "Suggestions", icon: Eye },
    { id: "recruiter", label: "Resume", icon: Download },
  ];

  return (
    <div className="min-h-screen">
      {/* Top Bar */}
      <div className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border">
        <div className="max-w-7xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button onClick={onReset} className="text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft size={18} />
            </button>
            <span className="text-sm font-semibold text-gradient-green">LexonPro</span>
            <span className="text-xs text-muted-foreground">/ {githubData.profile.login}</span>
          </div>
          <div className="flex items-center gap-2">
            {tabs.map((t) => (
              <button
                key={t.id}
                onClick={() => setTab(t.id)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${tab === t.id ? "bg-primary/10 text-primary" : "text-muted-foreground hover:text-foreground"}`}
              >
                {t.label}
              </button>
            ))}
            <button
              onClick={handleExportPDF}
              className="ml-2 px-3 py-1.5 rounded-lg text-xs font-medium bg-secondary text-muted-foreground hover:text-foreground transition-all inline-flex items-center gap-1.5"
            >
              <Download size={12} /> Export
            </button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left: Profile */}
          <div className="lg:col-span-4 xl:col-span-3">
            <div className="lg:sticky lg:top-20">
              <ProfileSummary profile={githubData.profile} stats={githubData.stats} analysis={analysis} />
            </div>
          </div>

          {/* Right: Content */}
          <div className="lg:col-span-8 xl:col-span-9">
            <motion.div
              key={tab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3 }}
            >
              {tab === "insights" && <InsightsPanel analysis={analysis} />}
              {tab === "suggestions" && <SuggestionsPanel analysis={analysis} />}
              {tab === "recruiter" && (
                <div className="space-y-4">
                  <InsightsPanel analysis={analysis} />
                  <SuggestionsPanel analysis={analysis} />
                </div>
              )}
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
